# Generated by Django 5.2.14 on 2026-05-29 13:05

import apps.products.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("brands", "0002_alter_brand_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("name", models.CharField(max_length=200, verbose_name="Naziv")),
                (
                    "name_sr",
                    models.CharField(max_length=200, null=True, verbose_name="Naziv"),
                ),
                (
                    "name_hu",
                    models.CharField(max_length=200, null=True, verbose_name="Naziv"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=200, null=True, verbose_name="Naziv"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "description_sr",
                    models.TextField(blank=True, null=True, verbose_name="Opis"),
                ),
                (
                    "description_hu",
                    models.TextField(blank=True, null=True, verbose_name="Opis"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Opis"),
                ),
                (
                    "key_features",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Ključne karakteristike"
                    ),
                ),
                (
                    "key_features_sr",
                    models.JSONField(
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="Ključne karakteristike",
                    ),
                ),
                (
                    "key_features_hu",
                    models.JSONField(
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="Ključne karakteristike",
                    ),
                ),
                (
                    "key_features_en",
                    models.JSONField(
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="Ključne karakteristike",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="products/main/",
                        verbose_name="Glavna slika",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Godina"
                    ),
                ),
                (
                    "price_eur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Cena (EUR)",
                    ),
                ),
                (
                    "horse_power",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Konjska snaga"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("new", "Novo"), ("used", "Polovno")],
                        default="new",
                        max_length=10,
                        verbose_name="Stanje",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Nacrt"),
                            ("published", "Objavljen"),
                            ("archived", "Arhiviran"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Objavljen"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="brands.brand",
                        verbose_name="Brend",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="brands.series",
                        verbose_name="Serija",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="brands.subcategory",
                        verbose_name="Potkategorija",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proizvod",
                "verbose_name_plural": "Proizvodi",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductBrochure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pdf_file",
                    models.FileField(
                        max_length=255,
                        upload_to="products/brochures/",
                        verbose_name="PDF brošura",
                    ),
                ),
                (
                    "cover_thumbnail_image",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="products/brochure_covers/",
                        verbose_name="Cover thumbnail",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Naslov brošure"
                    ),
                ),
                (
                    "title_sr",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Naslov brošure",
                    ),
                ),
                (
                    "title_hu",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Naslov brošure",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Naslov brošure",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brochures",
                        to="products.product",
                        verbose_name="Proizvod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brošura",
                "verbose_name_plural": "Brošure",
                "ordering": ["product", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        max_length=255,
                        upload_to="products/gallery/",
                        verbose_name="Slika",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Redosled"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt tekst"
                    ),
                ),
                (
                    "alt_text_sr",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Alt tekst"
                    ),
                ),
                (
                    "alt_text_hu",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Alt tekst"
                    ),
                ),
                (
                    "alt_text_en",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Alt tekst"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="Proizvod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Slika proizvoda",
                "verbose_name_plural": "Slike proizvoda",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductSimilar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Redosled"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_similars",
                        to="products.product",
                        verbose_name="Proizvod",
                    ),
                ),
                (
                    "related_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_similars",
                        to="products.product",
                        verbose_name="Sličan proizvod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sličan proizvod",
                "verbose_name_plural": "Slični proizvodi",
                "ordering": ["product", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("motor", "Motor"),
                            ("transmisija", "Transmisija"),
                            ("hidraulika", "Hidraulika"),
                            ("ostalo", "Ostalo"),
                        ],
                        db_index=True,
                        default="ostalo",
                        max_length=20,
                        verbose_name="Sekcija",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=200, verbose_name="Naziv specifikacije"
                    ),
                ),
                (
                    "key_sr",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Naziv specifikacije"
                    ),
                ),
                (
                    "key_hu",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Naziv specifikacije"
                    ),
                ),
                (
                    "key_en",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Naziv specifikacije"
                    ),
                ),
                ("value", models.CharField(max_length=200, verbose_name="Vrednost")),
                (
                    "value_sr",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Vrednost"
                    ),
                ),
                (
                    "value_hu",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Vrednost"
                    ),
                ),
                (
                    "value_en",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Vrednost"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Redosled"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="products.product",
                        verbose_name="Proizvod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Specifikacija",
                "verbose_name_plural": "Specifikacije",
                "ordering": ["product", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductTestimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="products/testimonials/",
                        verbose_name="Fotografija",
                    ),
                ),
                ("quote", models.TextField(verbose_name="Citat")),
                ("quote_sr", models.TextField(null=True, verbose_name="Citat")),
                ("quote_hu", models.TextField(null=True, verbose_name="Citat")),
                ("quote_en", models.TextField(null=True, verbose_name="Citat")),
                (
                    "author_name",
                    models.CharField(max_length=120, verbose_name="Ime autora"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Lokacija"
                    ),
                ),
                (
                    "location_sr",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="Lokacija"
                    ),
                ),
                (
                    "location_hu",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="Lokacija"
                    ),
                ),
                (
                    "location_en",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="Lokacija"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Redosled"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="products.product",
                        verbose_name="Proizvod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonijal",
                "verbose_name_plural": "Testimonijali",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Naziv")),
                (
                    "name_sr",
                    models.CharField(max_length=200, null=True, verbose_name="Naziv"),
                ),
                (
                    "name_hu",
                    models.CharField(max_length=200, null=True, verbose_name="Naziv"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=200, null=True, verbose_name="Naziv"),
                ),
                (
                    "code",
                    models.CharField(blank=True, max_length=50, verbose_name="Kod"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="products/variants/",
                        verbose_name="Slika varijante",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "description_sr",
                    models.TextField(blank=True, null=True, verbose_name="Opis"),
                ),
                (
                    "description_hu",
                    models.TextField(blank=True, null=True, verbose_name="Opis"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Opis"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Redosled"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                        verbose_name="Proizvod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Varijanta",
                "verbose_name_plural": "Varijante",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=apps.products.models._ProductIndex(
                fields=["is_published", "-created_at"],
                name="products_product_pub_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=apps.products.models._ProductIndex(
                fields=["brand", "status"], name="products_product_brand_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=apps.products.models._ProductIndex(
                fields=["condition", "is_published"],
                name="products_product_condition_pub_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productbrochure",
            index=apps.products.models._ProductIndex(
                fields=["product"], name="products_brochure_product_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=apps.products.models._ProductIndex(
                fields=["product", "order"], name="products_image_product_order_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productsimilar",
            index=apps.products.models._ProductIndex(
                fields=["product", "order"], name="products_similar_product_order_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productsimilar",
            constraint=models.UniqueConstraint(
                fields=("product", "related_product"),
                name="products_similar_pair_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="productsimilar",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("product", models.F("related_product")), _negated=True
                ),
                name="products_similar_no_self_reference",
            ),
        ),
        migrations.AddIndex(
            model_name="productspecification",
            index=apps.products.models._ProductIndex(
                fields=["product", "section", "order"],
                name="products_spec_product_section_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="producttestimonial",
            index=apps.products.models._ProductIndex(
                fields=["product", "order"],
                name="products_testimonial_product_order_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=apps.products.models._ProductIndex(
                fields=["product", "order"], name="products_variant_product_order_idx"
            ),
        ),
    ]
