# Generated by Django 5.2.14 on 2026-05-29 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True,
                validators=[django.core.validators.MaxLengthValidator(50000)],
                verbose_name="Opis",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_en",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(50000)],
                verbose_name="Opis",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_hu",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(50000)],
                verbose_name="Opis",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_sr",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(50000)],
                verbose_name="Opis",
            ),
        ),
        migrations.AlterField(
            model_name="producttestimonial",
            name="quote",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(50000)],
                verbose_name="Citat",
            ),
        ),
        migrations.AlterField(
            model_name="producttestimonial",
            name="quote_en",
            field=models.TextField(
                null=True,
                validators=[django.core.validators.MaxLengthValidator(50000)],
                verbose_name="Citat",
            ),
        ),
        migrations.AlterField(
            model_name="producttestimonial",
            name="quote_hu",
            field=models.TextField(
                null=True,
                validators=[django.core.validators.MaxLengthValidator(50000)],
                verbose_name="Citat",
            ),
        ),
        migrations.AlterField(
            model_name="producttestimonial",
            name="quote_sr",
            field=models.TextField(
                null=True,
                validators=[django.core.validators.MaxLengthValidator(50000)],
                verbose_name="Citat",
            ),
        ),
    ]
