# Generated by Django 5.2.14 on 2026-05-29 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="description",
            field=models.TextField(
                blank=True,
                validators=[django.core.validators.MaxLengthValidator(50000)],
                verbose_name="Opis",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="description_en",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(50000)],
                verbose_name="Opis",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="description_hu",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(50000)],
                verbose_name="Opis",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="description_sr",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(50000)],
                verbose_name="Opis",
            ),
        ),
    ]
