# Generated by Django 5.2.14 on 2026-05-29 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Naziv")),
                (
                    "name_sr",
                    models.CharField(max_length=120, null=True, verbose_name="Naziv"),
                ),
                (
                    "name_hu",
                    models.CharField(max_length=120, null=True, verbose_name="Naziv"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=120, null=True, verbose_name="Naziv"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=140, unique=True, verbose_name="Slug"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="brands/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="brands/heroes/",
                        verbose_name="Hero slika",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "description_sr",
                    models.TextField(blank=True, null=True, verbose_name="Opis"),
                ),
                (
                    "description_hu",
                    models.TextField(blank=True, null=True, verbose_name="Opis"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Opis"),
                ),
                (
                    "slogan",
                    models.CharField(blank=True, max_length=200, verbose_name="Slogan"),
                ),
                (
                    "slogan_sr",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Slogan"
                    ),
                ),
                (
                    "slogan_hu",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Slogan"
                    ),
                ),
                (
                    "slogan_en",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Slogan"
                    ),
                ),
                (
                    "statistics",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Statistike"
                    ),
                ),
                (
                    "catalog_pdf",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to="brands/catalogs/",
                        verbose_name="Katalog (PDF)",
                    ),
                ),
                (
                    "brand_color",
                    models.CharField(
                        blank=True, max_length=7, verbose_name="Brend boja"
                    ),
                ),
                (
                    "is_coming_soon",
                    models.BooleanField(default=False, verbose_name="Uskoro"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Kreiran"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ažuriran"),
                ),
            ],
            options={
                "verbose_name": "Brend",
                "verbose_name_plural": "Brendovi",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_coming_soon", "name"],
                        name="brands_brand_coming_name_idx",
                    ),
                    models.Index(
                        fields=["is_coming_soon", "name_sr"],
                        name="brands_bran_is_comi_e6af98_idx",
                    ),
                    models.Index(
                        fields=["is_coming_soon", "name_hu"],
                        name="brands_bran_is_comi_23c716_idx",
                    ),
                    models.Index(
                        fields=["is_coming_soon", "name_en"],
                        name="brands_bran_is_comi_c42cf3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Naziv")),
                (
                    "name_sr",
                    models.CharField(max_length=120, null=True, verbose_name="Naziv"),
                ),
                (
                    "name_hu",
                    models.CharField(max_length=120, null=True, verbose_name="Naziv"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=120, null=True, verbose_name="Naziv"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=140, unique=True, verbose_name="Slug"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "description_sr",
                    models.TextField(blank=True, null=True, verbose_name="Opis"),
                ),
                (
                    "description_hu",
                    models.TextField(blank=True, null=True, verbose_name="Opis"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Opis"),
                ),
                (
                    "is_for",
                    models.CharField(
                        choices=[
                            ("traktori", "Traktori"),
                            ("mehanizacija", "Mehanizacija"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Tip kataloga",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Redosled prikaza"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Ikona (Bootstrap Icons class)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kreirana"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ažurirana"),
                ),
            ],
            options={
                "verbose_name": "Kategorija",
                "verbose_name_plural": "Kategorije",
                "ordering": ["is_for", "display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_for", "display_order"],
                        name="brands_cat_scope_order_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Naziv")),
                (
                    "name_sr",
                    models.CharField(max_length=120, null=True, verbose_name="Naziv"),
                ),
                (
                    "name_hu",
                    models.CharField(max_length=120, null=True, verbose_name="Naziv"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=120, null=True, verbose_name="Naziv"),
                ),
                ("slug", models.SlugField(max_length=140, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "description_sr",
                    models.TextField(blank=True, null=True, verbose_name="Opis"),
                ),
                (
                    "description_hu",
                    models.TextField(blank=True, null=True, verbose_name="Opis"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Opis"),
                ),
                (
                    "layout_mode",
                    models.CharField(
                        choices=[("grid", "Grid"), ("extended", "Extended")],
                        default="grid",
                        max_length=10,
                        verbose_name="Režim prikaza",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Redosled prikaza"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kreirana"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ažurirana"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="series",
                        to="brands.brand",
                        verbose_name="Brend",
                    ),
                ),
            ],
            options={
                "verbose_name": "Serija",
                "verbose_name_plural": "Serije",
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["brand", "display_order"],
                        name="brands_series_brand_order_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("brand", "slug"), name="brands_series_brand_slug_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Naziv")),
                (
                    "name_sr",
                    models.CharField(max_length=120, null=True, verbose_name="Naziv"),
                ),
                (
                    "name_hu",
                    models.CharField(max_length=120, null=True, verbose_name="Naziv"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=120, null=True, verbose_name="Naziv"),
                ),
                ("slug", models.SlugField(max_length=140, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "description_sr",
                    models.TextField(blank=True, null=True, verbose_name="Opis"),
                ),
                (
                    "description_hu",
                    models.TextField(blank=True, null=True, verbose_name="Opis"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Opis"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Ikona (Bootstrap Icons class)",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Redosled prikaza"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kreirana"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ažurirana"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="brands.category",
                        verbose_name="Kategorija",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="brands.subcategory",
                        verbose_name="Roditeljska potkategorija",
                    ),
                ),
            ],
            options={
                "verbose_name": "Potkategorija",
                "verbose_name_plural": "Potkategorije",
                "ordering": ["category", "parent_id", "display_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["category", "parent", "display_order"],
                        name="brands_subcat_parent_order_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "parent", "slug"),
                        name="brands_subcategory_cat_parent_slug_unique",
                    )
                ],
            },
        ),
    ]
