# Generated by Django 5.2.14 on 2026-06-04 11:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Naziv')),
                ('name_sr', models.CharField(max_length=200, null=True, verbose_name='Naziv')),
                ('name_hu', models.CharField(max_length=200, null=True, verbose_name='Naziv')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Naziv')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('description_sr', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('description_hu', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Kategorija',
                'verbose_name_plural': 'Kategorije',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Naziv')),
                ('name_sr', models.CharField(max_length=100, null=True, verbose_name='Naziv')),
                ('name_hu', models.CharField(max_length=100, null=True, verbose_name='Naziv')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Naziv')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tagovi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Naslov')),
                ('title_sr', models.CharField(max_length=200, null=True, verbose_name='Naslov')),
                ('title_hu', models.CharField(max_length=200, null=True, verbose_name='Naslov')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Naslov')),
                ('perex', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(50000)], verbose_name='Perex')),
                ('perex_sr', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(50000)], verbose_name='Perex')),
                ('perex_hu', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(50000)], verbose_name='Perex')),
                ('perex_en', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(50000)], verbose_name='Perex')),
                ('body', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(50000)], verbose_name='Telo')),
                ('body_sr', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(50000)], verbose_name='Telo')),
                ('body_hu', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(50000)], verbose_name='Telo')),
                ('body_en', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(50000)], verbose_name='Telo')),
                ('main_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='blog/main/', verbose_name='Glavna slika')),
                ('status', models.CharField(choices=[('draft', 'Nacrt'), ('published', 'Objavljeno')], default='draft', max_length=12, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Datum objave')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Kategorija')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag', verbose_name='Tagovi')),
            ],
            options={
                'verbose_name': 'Objava',
                'verbose_name_plural': 'Objave',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='blog_post_status_pub_idx')],
            },
        ),
    ]
