# Generated by Django 5.2.14 on 2026-06-05 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(db_index=True, verbose_name='ID objekta')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta naslov')),
                ('meta_title_sr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta naslov')),
                ('meta_title_hu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta naslov')),
                ('meta_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta naslov')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta opis')),
                ('meta_description_sr', models.TextField(blank=True, null=True, verbose_name='Meta opis')),
                ('meta_description_hu', models.TextField(blank=True, null=True, verbose_name='Meta opis')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='Meta opis')),
                ('og_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='seo/og/', verbose_name='OG slika')),
                ('exclude_from_sitemap', models.BooleanField(db_index=True, default=False, verbose_name='Izostavi iz sitemap-a')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tip sadržaja')),
            ],
            options={
                'verbose_name': 'SEO meta',
                'verbose_name_plural': 'SEO meta',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='seo_seometa_ct_obj_uniq')],
            },
        ),
    ]
