# Generated by Django 5.2.14 on 2026-06-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_path', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Stari put')),
                ('new_path', models.CharField(max_length=255, verbose_name='Novi put')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktivno')),
            ],
            options={
                'verbose_name': 'Preusmerenje',
                'verbose_name_plural': 'Preusmerenja',
                'ordering': ['old_path'],
            },
        ),
    ]
