# Generated by Django 5.2.14 on 2026-06-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_type', models.CharField(choices=[('contact', 'Opšti kontakt'), ('model_inquiry', 'Upit za model'), ('service_request', 'Servisni zahtev'), ('part_request', 'Upit za rezervni deo')], max_length=20, verbose_name='Tip forme')),
                ('name', models.CharField(max_length=200, verbose_name='Ime')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('message', models.TextField(blank=True, verbose_name='Poruka')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Dodatni podaci')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP adresa')),
                ('locale', models.CharField(blank=True, default='sr', max_length=10, verbose_name='Jezik')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Lead-ovi',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['form_type', 'created_at'], name='forms_lead_type_created_idx')],
            },
        ),
    ]
