# Generated by Django 5.2.14 on 2026-06-04 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='leads/attachments/%Y/%m/', verbose_name='Datoteka')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='forms.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Prilog',
                'verbose_name_plural': 'Prilozi',
            },
        ),
    ]
