# Generated by Django 5.2.14 on 2026-06-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(default='Ćorić Agrar', max_length=200, verbose_name='Naziv firme')),
                ('slogan', models.CharField(blank=True, max_length=255, verbose_name='Slogan')),
                ('slogan_sr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Slogan')),
                ('slogan_hu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Slogan')),
                ('slogan_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Slogan')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresa')),
                ('address_sr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresa')),
                ('address_hu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresa')),
                ('address_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresa')),
                ('phone_sales', models.CharField(blank=True, max_length=50, verbose_name='Telefon prodaje')),
                ('phone_service', models.CharField(blank=True, help_text='PLACEHOLDER — privremena vrednost dok biznis ne unese realni broj servisa.', max_length=50, verbose_name='Telefon servisa')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-pošta')),
                ('working_hours', models.TextField(blank=True, help_text='Jedan red po liniji (npr. „Ponedeljak–Petak: 08–16h“).', verbose_name='Radno vreme')),
                ('working_hours_sr', models.TextField(blank=True, help_text='Jedan red po liniji (npr. „Ponedeljak–Petak: 08–16h“).', null=True, verbose_name='Radno vreme')),
                ('working_hours_hu', models.TextField(blank=True, help_text='Jedan red po liniji (npr. „Ponedeljak–Petak: 08–16h“).', null=True, verbose_name='Radno vreme')),
                ('working_hours_en', models.TextField(blank=True, help_text='Jedan red po liniji (npr. „Ponedeljak–Petak: 08–16h“).', null=True, verbose_name='Radno vreme')),
                ('social_facebook', models.URLField(blank=True, help_text='PLACEHOLDER — prazno dok biznis ne unese realni Facebook URL; link se sakriva kad je prazno.', verbose_name='Facebook URL')),
                ('social_instagram', models.URLField(blank=True, help_text='PLACEHOLDER — prazno dok biznis ne unese realni Instagram URL; link se sakriva kad je prazno.', verbose_name='Instagram URL')),
            ],
            options={
                'verbose_name': 'Podešavanja sajta',
                'verbose_name_plural': 'Podešavanja sajta',
            },
        ),
    ]
