# Generated by Django 5.2.14 on 2026-06-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_seed_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Naslov')),
                ('title_sr', models.CharField(max_length=255, null=True, verbose_name='Naslov')),
                ('title_hu', models.CharField(max_length=255, null=True, verbose_name='Naslov')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Naslov')),
                ('body', models.TextField(blank=True, verbose_name='Sadržaj')),
                ('body_sr', models.TextField(blank=True, null=True, verbose_name='Sadržaj')),
                ('body_hu', models.TextField(blank=True, null=True, verbose_name='Sadržaj')),
                ('body_en', models.TextField(blank=True, null=True, verbose_name='Sadržaj')),
            ],
            options={
                'verbose_name': 'Statička strana',
                'verbose_name_plural': 'Statičke strane',
                'ordering': ('title',),
            },
        ),
    ]
