# Generated by Django 5.2.14 on 2026-09-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_seed_privacy_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="social_youtube",
            field=models.URLField(
                blank=True,
                help_text="PLACEHOLDER — prazno dok biznis ne unese realni YouTube URL; link se sakriva kad je prazno.",
                verbose_name="YouTube URL",
            ),
        ),
    ]
