# Generated by Django 5.2.14 on 2026-06-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookiePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Naslov')),
                ('title_sr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Naslov')),
                ('title_hu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Naslov')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Naslov')),
                ('body', models.TextField(blank=True, verbose_name='Sadržaj')),
                ('body_sr', models.TextField(blank=True, null=True, verbose_name='Sadržaj')),
                ('body_hu', models.TextField(blank=True, null=True, verbose_name='Sadržaj')),
                ('body_en', models.TextField(blank=True, null=True, verbose_name='Sadržaj')),
                ('effective_date', models.DateField(blank=True, help_text='Pravni datum stupanja na snagu. Ažurirajte ga kad menjate sadržaj politike — ne ažurira se automatski.', null=True, verbose_name='Važi od')),
            ],
            options={
                'verbose_name': 'Politika kolačića',
                'verbose_name_plural': 'Politika kolačića',
            },
        ),
    ]
