"""Profil 2 — kurirani demo sadrzaj (1:1 snapshot lokalne baze), AUTO-GENERISAN.

NE UREDJUJ RUCNO — regenerisi kroz ``ops/seed/generate_profile2_manifest.py`` (cita
lokalnu bazu, kopira+optimizuje seed asset-e, ispisuje ovaj fajl). Rucne izmene ce biti
pregazene na sledecem pokretanju generatora.

Ovaj modul je CIST PODATAK. Seed logika (get_or_create po eksplicitnom slug-u,
modeltranslation `_sr` kolone, counters, atomicity, production guard, FileField attach-after-
create) zivi u ``seed_sample_data.py`` i deli se sa profilom 1 — ovde se NE pise logika.

Migracijski sadrzaj (brands/0003, brands/0004 — Jeegee/HZM/Tulip brend + prikljucne
kategorije/potkategorije + tulip-mix-6m3/8m3 proizvodi) je ISKLJUCEN — referenciran je kroz
``referenced_brand_slugs`` / ``referenced_category_slugs`` / ``subcategory_slug`` /
``brand_slug``, NE ponovo kreiran.

Pokretanje: ``just dev-manage seed_sample_data --profile=2``
"""

from __future__ import annotations

from decimal import Decimal

PROFILE_2: dict = {
    "tractor_brands": [
        {
            "slug": "agri-tracking",
            "name": "Agri Tracking",
            "description": "Moderni traktori sa naprednom hidraulikom i klimatizovanom kabinom.",
            "slogan": "Tehnologija u službi zemlje.",
            "brand_color": "#000000",
            "statistics": [
                {
                    "label": "Prodatih modela",
                    "value": 1500,
                },
                {
                    "label": "Zaposlenih",
                    "value": 100,
                },
                {
                    "label": "Pogona",
                    "value": 13,
                },
                {
                    "label": "Godina poslovanja",
                    "value": 15,
                },
            ],
            "logo_asset": "agri-tracking-logo.jpg",
            "hero_image_asset": "agri-tracking-hero.jpg",
        },
        {
            "slug": "saillong",
            "name": "Saillong",
            "description": "Robusni traktori velike snage za zahtevne ratarske radove.",
            "slogan": "Stvoreni za teren.",
            "brand_color": "#000000",
            "logo_asset": "saillong-logo.jpg",
        },
        {
            "slug": "wuzheng",
            "name": "Wuzheng",
            "description": "Pouzdani traktori za male i srednje poljoprivredne posede.",
            "slogan": "Snaga koja traje.",
        },
    ],
    "referenced_brand_slugs": (
        "hzm",
        "jeegee",
        "tulip",
    ),
    "traktori_category": {
        "slug": "traktori",
        "name": "Traktori",
        "is_for": "traktori",
        "display_order": 10,
        "description": "Poljoprivredni traktori — nova i polovna mehanizacija za sve veličine gazdinstva.",
    },
    "referenced_category_slugs": (
        "masine-za-setvu",
        "osnovna-obrada-zemljista",
        "priprema-zemljista",
        "radne-masine",
    ),
    "subcategories": [
        {
            "slug": "sejalice",
            "category_slug": "masine-za-setvu",
            "name": "Sejalice",
            "description": "",
            "icon": "",
            "display_order": 0,
        },
        {
            "slug": "plugovi",
            "category_slug": "osnovna-obrada-zemljista",
            "name": "Plugovi",
            "description": "",
            "icon": "",
            "display_order": 0,
        },
        {
            "slug": "tanjirace",
            "category_slug": "priprema-zemljista",
            "name": "Tanjirače",
            "description": "",
            "icon": "",
            "display_order": 0,
        },
        {
            "slug": "mini-utovarivaci",
            "category_slug": "radne-masine",
            "name": "Mini utovarivači",
            "description": "",
            "icon": "",
            "display_order": 10,
        },
        {
            "slug": "telehendleri",
            "category_slug": "radne-masine",
            "name": "Telehendleri",
            "description": "",
            "icon": "",
            "display_order": 40,
        },
        {
            "slug": "teleskopski-utovarivaci",
            "category_slug": "radne-masine",
            "name": "Teleskopski utovarivači",
            "description": "",
            "icon": "",
            "display_order": 30,
        },
        {
            "slug": "utovarivaci-bez-teleskopa",
            "category_slug": "radne-masine",
            "name": "Utovarivači bez teleskopa",
            "description": "",
            "icon": "",
            "display_order": 20,
        },
        {
            "slug": "traktori",
            "category_slug": "traktori",
            "name": "Traktori",
            "description": "",
            "icon": "",
            "display_order": 0,
        },
    ],
    "series": [
        {
            "brand_slug": "agri-tracking",
            "slug": "premium-serija",
            "name": "Premium serija",
            "description": "",
            "layout_mode": "extended",
            "display_order": 1,
        },
        {
            "brand_slug": "agri-tracking",
            "slug": "standardna-serija",
            "name": "Standardna serija",
            "description": "",
            "layout_mode": "grid",
            "display_order": 0,
        },
        {
            "brand_slug": "saillong",
            "slug": "standardna-serija",
            "name": "Standardna serija",
            "description": "",
            "layout_mode": "grid",
            "display_order": 0,
        },
        {
            "brand_slug": "wuzheng",
            "slug": "standardna-serija",
            "name": "Standardna serija",
            "description": "",
            "layout_mode": "grid",
            "display_order": 0,
        },
    ],
    "new_tractors": [
        {
            "slug": "agri-tracking-tb1004",
            "brand_slug": "agri-tracking",
            "name": "Agri Tracking TB1004",
            "description": "Vrhunski model sa klimatizovanom kabinom i GPS pripremom.",
            "key_features": [
                "Klimatizovana kabina",
                "Hidraulična dizalica",
                "Robusna konstrukcija",
            ],
            "horse_power": 100,
            "year": 2025,
            "price_eur": Decimal("34900.00"),
            "subcategory_slug": "traktori",
            "series_slug": "standardna-serija",
            "main_image_asset": "agri-tracking-tb1004-main.jpg",
            "images": [
                {
                    "asset": "agri-tracking-tb1004-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Agri Tracking TB1004",
                },
                {
                    "asset": "agri-tracking-real-10.jpg",
                    "order": 1,
                    "alt_text": "Agri Tracking TB1004 — galerija 1",
                },
                {
                    "asset": "agri-tracking-real-08.jpg",
                    "order": 2,
                    "alt_text": "Agri Tracking TB1004 — galerija 2",
                },
                {
                    "asset": "agri-tracking-real-27.jpg",
                    "order": 3,
                    "alt_text": "Agri Tracking TB1004 — galerija 3",
                },
                {
                    "asset": "agri-tracking-real-06.jpg",
                    "order": 4,
                    "alt_text": "Agri Tracking TB1004 — galerija 4",
                },
                {
                    "asset": "agri-tracking-real-23.jpg",
                    "order": 5,
                    "alt_text": "Agri Tracking TB1004 — galerija 5",
                },
                {
                    "asset": "agri-tracking-real-29.jpg",
                    "order": 6,
                    "alt_text": "Agri Tracking TB1004 — galerija 6",
                },
                {
                    "asset": "agri-tracking-real-03.jpg",
                    "order": 7,
                    "alt_text": "Agri Tracking TB1004 — galerija 7",
                },
                {
                    "asset": "agri-tracking-real-19.jpg",
                    "order": 8,
                    "alt_text": "Agri Tracking TB1004 — galerija 8",
                },
                {
                    "asset": "agri-tracking-real-30.jpg",
                    "order": 9,
                    "alt_text": "Agri Tracking TB1004 — galerija 9",
                },
                {
                    "asset": "agri-tracking-real-17.jpg",
                    "order": 10,
                    "alt_text": "Agri Tracking TB1004 — galerija 10",
                },
                {
                    "asset": "agri-tracking-real-16.jpg",
                    "order": 11,
                    "alt_text": "Agri Tracking TB1004 — galerija 11",
                },
                {
                    "asset": "agri-tracking-real-11.jpg",
                    "order": 12,
                    "alt_text": "Agri Tracking TB1004 — galerija 12",
                },
                {
                    "asset": "agri-tracking-real-15.jpg",
                    "order": 13,
                    "alt_text": "Agri Tracking TB1004 — galerija 13",
                },
                {
                    "asset": "agri-tracking-real-21.jpg",
                    "order": 14,
                    "alt_text": "Agri Tracking TB1004 — galerija 14",
                },
                {
                    "asset": "agri-tracking-real-22.jpg",
                    "order": 15,
                    "alt_text": "Agri Tracking TB1004 — galerija 15",
                },
            ],
        },
        {
            "slug": "agri-tracking-tb604",
            "brand_slug": "agri-tracking",
            "name": "Agri Tracking TB604",
            "description": "Kompaktan traktor za manje i srednje parcele.",
            "key_features": [
                "Klimatizovana kabina",
                "Hidraulična dizalica",
                "Robusna konstrukcija",
            ],
            "horse_power": 60,
            "year": 2023,
            "price_eur": Decimal("23600.00"),
            "subcategory_slug": "traktori",
            "series_slug": "standardna-serija",
            "main_image_asset": "agri-tracking-tb604-main.jpg",
            "images": [
                {
                    "asset": "agri-tracking-tb604-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Agri Tracking TB604",
                },
                {
                    "asset": "agri-tracking-real-11.jpg",
                    "order": 1,
                    "alt_text": "Agri Tracking TB604 — galerija 1",
                },
                {
                    "asset": "agri-tracking-real-05.jpg",
                    "order": 2,
                    "alt_text": "Agri Tracking TB604 — galerija 2",
                },
                {
                    "asset": "agri-tracking-real-13.jpg",
                    "order": 3,
                    "alt_text": "Agri Tracking TB604 — galerija 3",
                },
                {
                    "asset": "agri-tracking-real-21.jpg",
                    "order": 4,
                    "alt_text": "Agri Tracking TB604 — galerija 4",
                },
                {
                    "asset": "agri-tracking-real-02.jpg",
                    "order": 5,
                    "alt_text": "Agri Tracking TB604 — galerija 5",
                },
                {
                    "asset": "agri-tracking-real-03.jpg",
                    "order": 6,
                    "alt_text": "Agri Tracking TB604 — galerija 6",
                },
                {
                    "asset": "agri-tracking-real-18.jpg",
                    "order": 7,
                    "alt_text": "Agri Tracking TB604 — galerija 7",
                },
                {
                    "asset": "agri-tracking-real-04.jpg",
                    "order": 8,
                    "alt_text": "Agri Tracking TB604 — galerija 8",
                },
                {
                    "asset": "agri-tracking-real-12.jpg",
                    "order": 9,
                    "alt_text": "Agri Tracking TB604 — galerija 9",
                },
                {
                    "asset": "agri-tracking-real-19.jpg",
                    "order": 10,
                    "alt_text": "Agri Tracking TB604 — galerija 10",
                },
                {
                    "asset": "agri-tracking-real-25.jpg",
                    "order": 11,
                    "alt_text": "Agri Tracking TB604 — galerija 11",
                },
                {
                    "asset": "agri-tracking-real-17.jpg",
                    "order": 12,
                    "alt_text": "Agri Tracking TB604 — galerija 12",
                },
                {
                    "asset": "agri-tracking-real-07.jpg",
                    "order": 13,
                    "alt_text": "Agri Tracking TB604 — galerija 13",
                },
                {
                    "asset": "agri-tracking-real-20.jpg",
                    "order": 14,
                    "alt_text": "Agri Tracking TB604 — galerija 14",
                },
                {
                    "asset": "agri-tracking-real-16.jpg",
                    "order": 15,
                    "alt_text": "Agri Tracking TB604 — galerija 15",
                },
            ],
        },
        {
            "slug": "agri-tracking-tb704",
            "brand_slug": "agri-tracking",
            "name": "Agri Tracking TB704",
            "description": "Pouzdan traktor srednje snage za svakodnevnu upotrebu.",
            "key_features": [
                "Klimatizovana kabina",
                "Hidraulična dizalica",
                "Robusna konstrukcija",
            ],
            "horse_power": 70,
            "year": 2023,
            "price_eur": Decimal("26700.00"),
            "subcategory_slug": "traktori",
            "series_slug": "standardna-serija",
            "main_image_asset": "agri-tracking-tb704-main.jpg",
            "images": [
                {
                    "asset": "agri-tracking-tb704-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Agri Tracking TB704",
                },
                {
                    "asset": "agri-tracking-real-14.jpg",
                    "order": 1,
                    "alt_text": "Agri Tracking TB704 — galerija 1",
                },
                {
                    "asset": "agri-tracking-real-30.jpg",
                    "order": 2,
                    "alt_text": "Agri Tracking TB704 — galerija 2",
                },
                {
                    "asset": "agri-tracking-real-03.jpg",
                    "order": 3,
                    "alt_text": "Agri Tracking TB704 — galerija 3",
                },
                {
                    "asset": "agri-tracking-real-08.jpg",
                    "order": 4,
                    "alt_text": "Agri Tracking TB704 — galerija 4",
                },
                {
                    "asset": "agri-tracking-real-28.jpg",
                    "order": 5,
                    "alt_text": "Agri Tracking TB704 — galerija 5",
                },
                {
                    "asset": "agri-tracking-real-18.jpg",
                    "order": 6,
                    "alt_text": "Agri Tracking TB704 — galerija 6",
                },
                {
                    "asset": "agri-tracking-real-29.jpg",
                    "order": 7,
                    "alt_text": "Agri Tracking TB704 — galerija 7",
                },
                {
                    "asset": "agri-tracking-real-02.jpg",
                    "order": 8,
                    "alt_text": "Agri Tracking TB704 — galerija 8",
                },
                {
                    "asset": "agri-tracking-real-19.jpg",
                    "order": 9,
                    "alt_text": "Agri Tracking TB704 — galerija 9",
                },
                {
                    "asset": "agri-tracking-real-04.jpg",
                    "order": 10,
                    "alt_text": "Agri Tracking TB704 — galerija 10",
                },
                {
                    "asset": "agri-tracking-real-27.jpg",
                    "order": 11,
                    "alt_text": "Agri Tracking TB704 — galerija 11",
                },
                {
                    "asset": "agri-tracking-real-22.jpg",
                    "order": 12,
                    "alt_text": "Agri Tracking TB704 — galerija 12",
                },
                {
                    "asset": "agri-tracking-real-13.jpg",
                    "order": 13,
                    "alt_text": "Agri Tracking TB704 — galerija 13",
                },
                {
                    "asset": "agri-tracking-real-24.jpg",
                    "order": 14,
                    "alt_text": "Agri Tracking TB704 — galerija 14",
                },
                {
                    "asset": "agri-tracking-real-20.jpg",
                    "order": 15,
                    "alt_text": "Agri Tracking TB704 — galerija 15",
                },
            ],
            "specs": [
                {
                    "section": "hidraulika",
                    "key": "Nosivost dizalice",
                    "value": "1800 kg",
                    "order": 0,
                },
                {
                    "section": "hidraulika",
                    "key": "Protok hidraulicne pumpe",
                    "value": "45 L/min",
                    "order": 1,
                },
                {
                    "section": "motor",
                    "key": "Tip motora",
                    "value": "A498BT-6A",
                    "order": 0,
                },
                {
                    "section": "motor",
                    "key": "Nominalna snaga (kW/KS)",
                    "value": "51.5kw, 70ks",
                    "order": 1,
                },
                {
                    "section": "motor",
                    "key": "Broj cilindara",
                    "value": "4",
                    "order": 2,
                },
                {
                    "section": "motor",
                    "key": "Zapremina motora",
                    "value": "3,76L",
                    "order": 3,
                },
                {
                    "section": "motor",
                    "key": "Nominalni broj obrtaja (o/min)",
                    "value": "2400",
                    "order": 4,
                },
                {
                    "section": "motor",
                    "key": "Rezervoar za gorivo (L)",
                    "value": "80",
                    "order": 5,
                },
                {
                    "section": "ostalo",
                    "key": "Masa vozila",
                    "value": "2450 kg",
                    "order": 0,
                },
                {
                    "section": "ostalo",
                    "key": "Tocak (prednji/zadnji)",
                    "value": "9.5-20 / 14.9-28",
                    "order": 1,
                },
                {
                    "section": "transmisija",
                    "key": "Broj brzina",
                    "value": "12+12",
                    "order": 0,
                },
                {
                    "section": "transmisija",
                    "key": "Tip transmisije",
                    "value": "Mehanicka, sinhronizovana",
                    "order": 1,
                },
            ],
        },
        {
            "slug": "agri-tracking-tb804",
            "brand_slug": "agri-tracking",
            "name": "Agri Tracking TB804",
            "description": "Univerzalni traktor od 80 KS sa klimatizovanom kabinom i hidrauličnom dizalicom.",
            "key_features": [
                "Klimatizovana kabina",
                "Hidraulična dizalica",
                "Robusna konstrukcija",
            ],
            "horse_power": 80,
            "year": 2024,
            "price_eur": Decimal("28500.00"),
            "subcategory_slug": "traktori",
            "series_slug": "premium-serija",
            "main_image_asset": "agri-tracking-tb804-main.jpg",
            "images": [
                {
                    "asset": "agri-tracking-tb804-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Agri Tracking TB804",
                },
                {
                    "asset": "agri-tracking-real-02.jpg",
                    "order": 1,
                    "alt_text": "Agri Tracking TB804 — galerija 1",
                },
                {
                    "asset": "agri-tracking-real-18.jpg",
                    "order": 2,
                    "alt_text": "Agri Tracking TB804 — galerija 2",
                },
                {
                    "asset": "agri-tracking-real-05.jpg",
                    "order": 3,
                    "alt_text": "Agri Tracking TB804 — galerija 3",
                },
                {
                    "asset": "agri-tracking-real-10.jpg",
                    "order": 4,
                    "alt_text": "Agri Tracking TB804 — galerija 4",
                },
                {
                    "asset": "agri-tracking-real-14.jpg",
                    "order": 5,
                    "alt_text": "Agri Tracking TB804 — galerija 5",
                },
                {
                    "asset": "agri-tracking-real-28.jpg",
                    "order": 6,
                    "alt_text": "Agri Tracking TB804 — galerija 6",
                },
                {
                    "asset": "agri-tracking-real-29.jpg",
                    "order": 7,
                    "alt_text": "Agri Tracking TB804 — galerija 7",
                },
                {
                    "asset": "agri-tracking-real-04.jpg",
                    "order": 8,
                    "alt_text": "Agri Tracking TB804 — galerija 8",
                },
                {
                    "asset": "agri-tracking-real-19.jpg",
                    "order": 9,
                    "alt_text": "Agri Tracking TB804 — galerija 9",
                },
                {
                    "asset": "agri-tracking-real-27.jpg",
                    "order": 10,
                    "alt_text": "Agri Tracking TB804 — galerija 10",
                },
                {
                    "asset": "agri-tracking-real-23.jpg",
                    "order": 11,
                    "alt_text": "Agri Tracking TB804 — galerija 11",
                },
                {
                    "asset": "agri-tracking-real-06.jpg",
                    "order": 12,
                    "alt_text": "Agri Tracking TB804 — galerija 12",
                },
                {
                    "asset": "agri-tracking-real-22.jpg",
                    "order": 13,
                    "alt_text": "Agri Tracking TB804 — galerija 13",
                },
                {
                    "asset": "agri-tracking-real-07.jpg",
                    "order": 14,
                    "alt_text": "Agri Tracking TB804 — galerija 14",
                },
                {
                    "asset": "agri-tracking-real-21.jpg",
                    "order": 15,
                    "alt_text": "Agri Tracking TB804 — galerija 15",
                },
            ],
            "specs": [
                {
                    "section": "hidraulika",
                    "key": "Nosivost dizalice",
                    "value": "2600 kg",
                    "order": 2,
                },
                {
                    "section": "motor",
                    "key": "Snaga motora",
                    "value": "80 KS",
                    "order": 0,
                },
                {
                    "section": "ostalo",
                    "key": "Masa vozila",
                    "value": "1950 kg",
                    "order": 0,
                },
                {
                    "section": "transmisija",
                    "key": "Broj brzina",
                    "value": "16+8",
                    "order": 1,
                },
            ],
        },
        {
            "slug": "agri-tracking-tb904",
            "brand_slug": "agri-tracking",
            "name": "Agri Tracking TB904",
            "description": "Snažan traktor sa naprednom hidraulikom za teže radove.",
            "key_features": [
                "Klimatizovana kabina",
                "Hidraulična dizalica",
                "Robusna konstrukcija",
            ],
            "horse_power": 90,
            "year": 2024,
            "price_eur": Decimal("31200.00"),
            "subcategory_slug": "traktori",
            "series_slug": "standardna-serija",
            "main_image_asset": "agri-tracking-tb904-main.jpg",
            "images": [
                {
                    "asset": "agri-tracking-tb904-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Agri Tracking TB904",
                },
                {
                    "asset": "agri-tracking-real-04.jpg",
                    "order": 1,
                    "alt_text": "Agri Tracking TB904 — galerija 1",
                },
                {
                    "asset": "agri-tracking-real-18.jpg",
                    "order": 2,
                    "alt_text": "Agri Tracking TB904 — galerija 2",
                },
                {
                    "asset": "agri-tracking-real-23.jpg",
                    "order": 3,
                    "alt_text": "Agri Tracking TB904 — galerija 3",
                },
                {
                    "asset": "agri-tracking-real-03.jpg",
                    "order": 4,
                    "alt_text": "Agri Tracking TB904 — galerija 4",
                },
                {
                    "asset": "agri-tracking-real-19.jpg",
                    "order": 5,
                    "alt_text": "Agri Tracking TB904 — galerija 5",
                },
                {
                    "asset": "agri-tracking-real-02.jpg",
                    "order": 6,
                    "alt_text": "Agri Tracking TB904 — galerija 6",
                },
                {
                    "asset": "agri-tracking-real-20.jpg",
                    "order": 7,
                    "alt_text": "Agri Tracking TB904 — galerija 7",
                },
                {
                    "asset": "agri-tracking-real-07.jpg",
                    "order": 8,
                    "alt_text": "Agri Tracking TB904 — galerija 8",
                },
                {
                    "asset": "agri-tracking-real-16.jpg",
                    "order": 9,
                    "alt_text": "Agri Tracking TB904 — galerija 9",
                },
                {
                    "asset": "agri-tracking-real-29.jpg",
                    "order": 10,
                    "alt_text": "Agri Tracking TB904 — galerija 10",
                },
                {
                    "asset": "agri-tracking-real-14.jpg",
                    "order": 11,
                    "alt_text": "Agri Tracking TB904 — galerija 11",
                },
                {
                    "asset": "agri-tracking-real-11.jpg",
                    "order": 12,
                    "alt_text": "Agri Tracking TB904 — galerija 12",
                },
                {
                    "asset": "agri-tracking-real-15.jpg",
                    "order": 13,
                    "alt_text": "Agri Tracking TB904 — galerija 13",
                },
                {
                    "asset": "agri-tracking-real-17.jpg",
                    "order": 14,
                    "alt_text": "Agri Tracking TB904 — galerija 14",
                },
                {
                    "asset": "agri-tracking-real-06.jpg",
                    "order": 15,
                    "alt_text": "Agri Tracking TB904 — galerija 15",
                },
            ],
        },
        {
            "slug": "hzm-ml-15",
            "brand_slug": "hzm",
            "name": "HZM ML-15",
            "description": "Kompaktan mini utovarivač za rad u tesnim prostorima.",
            "key_features": [
                "Pouzdana hidraulika",
                "Robusna konstrukcija",
                "Servisna podrška",
            ],
            "horse_power": 15,
            "year": 2024,
            "price_eur": Decimal("8200.00"),
            "subcategory_slug": "mini-utovarivaci",
            "main_image_asset": "hzm-ml-15-main.jpg",
            "images": [
                {
                    "asset": "hzm-ml-15-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "HZM ML-15",
                },
            ],
        },
        {
            "slug": "hzm-ml-20",
            "brand_slug": "hzm",
            "name": "HZM ML-20",
            "description": "Mini utovarivač sa pojačanom hidraulikom za svakodnevnu upotrebu.",
            "key_features": [
                "Pouzdana hidraulika",
                "Robusna konstrukcija",
                "Servisna podrška",
            ],
            "horse_power": 20,
            "year": 2024,
            "price_eur": Decimal("9600.00"),
            "subcategory_slug": "mini-utovarivaci",
            "main_image_asset": "hzm-ml-20-main.jpg",
            "images": [
                {
                    "asset": "hzm-ml-20-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "HZM ML-20",
                },
            ],
        },
        {
            "slug": "hzm-ml-25",
            "brand_slug": "hzm",
            "name": "HZM ML-25",
            "description": "Univerzalni mini utovarivač pogodan za farme i manje objekte.",
            "key_features": [
                "Pouzdana hidraulika",
                "Robusna konstrukcija",
                "Servisna podrška",
            ],
            "horse_power": 25,
            "year": 2023,
            "price_eur": Decimal("11200.00"),
            "subcategory_slug": "mini-utovarivaci",
            "main_image_asset": "hzm-ml-25-main.jpg",
            "images": [
                {
                    "asset": "hzm-ml-25-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "HZM ML-25",
                },
            ],
        },
        {
            "slug": "hzm-ml-30",
            "brand_slug": "hzm",
            "name": "HZM ML-30",
            "description": "Snažniji mini utovarivač sa brzim prilaznim sistemom.",
            "key_features": [
                "Pouzdana hidraulika",
                "Robusna konstrukcija",
                "Servisna podrška",
            ],
            "horse_power": 30,
            "year": 2023,
            "price_eur": Decimal("12900.00"),
            "subcategory_slug": "mini-utovarivaci",
            "main_image_asset": "hzm-ml-30-main.jpg",
            "images": [
                {
                    "asset": "hzm-ml-30-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "HZM ML-30",
                },
            ],
        },
        {
            "slug": "hzm-th-25",
            "brand_slug": "hzm",
            "name": "HZM TH-25",
            "description": "Kompaktan telehendler za rad u skladištima i farmama.",
            "key_features": [
                "Pouzdana hidraulika",
                "Robusna konstrukcija",
                "Servisna podrška",
            ],
            "horse_power": 25,
            "year": 2024,
            "price_eur": Decimal("22100.00"),
            "subcategory_slug": "telehendleri",
            "main_image_asset": "hzm-th-25-main.jpg",
            "images": [
                {
                    "asset": "hzm-th-25-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "HZM TH-25",
                },
            ],
        },
        {
            "slug": "hzm-th-30",
            "brand_slug": "hzm",
            "name": "HZM TH-30",
            "description": "Telehendler sa stabilnom osovinom i udobnom kabinom.",
            "key_features": [
                "Pouzdana hidraulika",
                "Robusna konstrukcija",
                "Servisna podrška",
            ],
            "horse_power": 30,
            "year": 2024,
            "price_eur": Decimal("24600.00"),
            "subcategory_slug": "telehendleri",
            "main_image_asset": "hzm-th-30-main.jpg",
            "images": [
                {
                    "asset": "hzm-th-30-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "HZM TH-30",
                },
            ],
        },
        {
            "slug": "hzm-th-35",
            "brand_slug": "hzm",
            "name": "HZM TH-35",
            "description": "Telehendler povećane nosivosti za teže terete.",
            "key_features": [
                "Pouzdana hidraulika",
                "Robusna konstrukcija",
                "Servisna podrška",
            ],
            "horse_power": 35,
            "year": 2023,
            "price_eur": Decimal("27900.00"),
            "subcategory_slug": "telehendleri",
            "main_image_asset": "hzm-th-35-main.jpg",
            "images": [
                {
                    "asset": "hzm-th-35-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "HZM TH-35",
                },
            ],
        },
        {
            "slug": "hzm-th-45",
            "brand_slug": "hzm",
            "name": "HZM TH-45",
            "description": "Najsnažniji telehendler u ponudi, za profesionalnu upotrebu.",
            "key_features": [
                "Pouzdana hidraulika",
                "Robusna konstrukcija",
                "Servisna podrška",
            ],
            "horse_power": 45,
            "year": 2023,
            "price_eur": Decimal("31200.00"),
            "subcategory_slug": "telehendleri",
            "main_image_asset": "hzm-th-45-main.jpg",
            "images": [
                {
                    "asset": "hzm-th-45-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "HZM TH-45",
                },
            ],
        },
        {
            "slug": "hzm-tl-100",
            "brand_slug": "hzm",
            "name": "HZM TL-100",
            "description": "Vrhunski model sa najvećim dometom u TL seriji.",
            "key_features": [
                "Pouzdana hidraulika",
                "Robusna konstrukcija",
                "Servisna podrška",
            ],
            "horse_power": 100,
            "year": 2023,
            "price_eur": Decimal("33400.00"),
            "subcategory_slug": "teleskopski-utovarivaci",
            "main_image_asset": "hzm-tl-100-main.jpg",
            "images": [
                {
                    "asset": "hzm-tl-100-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "HZM TL-100",
                },
            ],
        },
        {
            "slug": "hzm-tl-60",
            "brand_slug": "hzm",
            "name": "HZM TL-60",
            "description": "Teleskopski utovarivač sa produženim dohvatom za visoke tovare.",
            "key_features": [
                "Pouzdana hidraulika",
                "Robusna konstrukcija",
                "Servisna podrška",
            ],
            "horse_power": 60,
            "year": 2024,
            "price_eur": Decimal("24800.00"),
            "subcategory_slug": "teleskopski-utovarivaci",
            "main_image_asset": "hzm-tl-60-main.jpg",
            "images": [
                {
                    "asset": "hzm-tl-60-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "HZM TL-60",
                },
            ],
        },
        {
            "slug": "hzm-tl-70",
            "brand_slug": "hzm",
            "name": "HZM TL-70",
            "description": "Teleskopski utovarivač sa preciznom hidrauličkom kontrolom.",
            "key_features": [
                "Pouzdana hidraulika",
                "Robusna konstrukcija",
                "Servisna podrška",
            ],
            "horse_power": 70,
            "year": 2024,
            "price_eur": Decimal("27200.00"),
            "subcategory_slug": "teleskopski-utovarivaci",
            "main_image_asset": "hzm-tl-70-main.jpg",
            "images": [
                {
                    "asset": "hzm-tl-70-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "HZM TL-70",
                },
            ],
        },
        {
            "slug": "hzm-tl-80",
            "brand_slug": "hzm",
            "name": "HZM TL-80",
            "description": "Snažan teleskopski utovarivač za rad na velikim gazdinstvima.",
            "key_features": [
                "Pouzdana hidraulika",
                "Robusna konstrukcija",
                "Servisna podrška",
            ],
            "horse_power": 80,
            "year": 2023,
            "price_eur": Decimal("29900.00"),
            "subcategory_slug": "teleskopski-utovarivaci",
            "main_image_asset": "hzm-tl-80-main.jpg",
            "images": [
                {
                    "asset": "hzm-tl-80-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "HZM TL-80",
                },
            ],
        },
        {
            "slug": "hzm-ub-40",
            "brand_slug": "hzm",
            "name": "HZM UB-40",
            "description": "Utovarivač bez teleskopa sa robusnom čeonom konstrukcijom.",
            "key_features": [
                "Pouzdana hidraulika",
                "Robusna konstrukcija",
                "Servisna podrška",
            ],
            "horse_power": 40,
            "year": 2024,
            "price_eur": Decimal("16400.00"),
            "subcategory_slug": "utovarivaci-bez-teleskopa",
            "main_image_asset": "hzm-ub-40-main.jpg",
            "images": [
                {
                    "asset": "hzm-ub-40-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "HZM UB-40",
                },
            ],
        },
        {
            "slug": "hzm-ub-45",
            "brand_slug": "hzm",
            "name": "HZM UB-45",
            "description": "Pouzdan utovarivač za transport i utovar rasutog materijala.",
            "key_features": [
                "Pouzdana hidraulika",
                "Robusna konstrukcija",
                "Servisna podrška",
            ],
            "horse_power": 45,
            "year": 2024,
            "price_eur": Decimal("17800.00"),
            "subcategory_slug": "utovarivaci-bez-teleskopa",
            "main_image_asset": "hzm-ub-45-main.jpg",
            "images": [
                {
                    "asset": "hzm-ub-45-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "HZM UB-45",
                },
            ],
        },
        {
            "slug": "hzm-ub-50",
            "brand_slug": "hzm",
            "name": "HZM UB-50",
            "description": "Utovarivač povećane nosivosti za intenzivan rad.",
            "key_features": [
                "Pouzdana hidraulika",
                "Robusna konstrukcija",
                "Servisna podrška",
            ],
            "horse_power": 50,
            "year": 2023,
            "price_eur": Decimal("19200.00"),
            "subcategory_slug": "utovarivaci-bez-teleskopa",
            "main_image_asset": "hzm-ub-50-main.jpg",
            "images": [
                {
                    "asset": "hzm-ub-50-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "HZM UB-50",
                },
            ],
        },
        {
            "slug": "hzm-ub-60",
            "brand_slug": "hzm",
            "name": "HZM UB-60",
            "description": "Najsnažniji model u UB liniji, pogodan za stočarske farme.",
            "key_features": [
                "Pouzdana hidraulika",
                "Robusna konstrukcija",
                "Servisna podrška",
            ],
            "horse_power": 60,
            "year": 2023,
            "price_eur": Decimal("21500.00"),
            "subcategory_slug": "utovarivaci-bez-teleskopa",
            "main_image_asset": "hzm-ub-60-main.jpg",
            "images": [
                {
                    "asset": "hzm-ub-60-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "HZM UB-60",
                },
            ],
        },
        {
            "slug": "jeegee-pl-2r",
            "brand_slug": "jeegee",
            "name": "Jeegee PL-2R",
            "description": "Dvorazni reverzibilni plug za manje parcele.",
            "key_features": [
                "Robusna konstrukcija",
                "Jednostavno održavanje",
                "Prilagodljivo traktorima",
            ],
            "horse_power": None,
            "year": None,
            "price_eur": None,
            "subcategory_slug": "plugovi",
            "main_image_asset": "jeegee-pl-2r-main.jpg",
            "images": [
                {
                    "asset": "jeegee-pl-2r-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Jeegee PL-2R",
                },
            ],
        },
        {
            "slug": "jeegee-pl-3",
            "brand_slug": "jeegee",
            "name": "Jeegee PL-3",
            "description": "Trorazni plug za srednje traktore, pojačana konstrukcija.",
            "key_features": [
                "Robusna konstrukcija",
                "Jednostavno održavanje",
                "Prilagodljivo traktorima",
            ],
            "horse_power": None,
            "year": None,
            "price_eur": None,
            "subcategory_slug": "plugovi",
            "main_image_asset": "jeegee-pl-3-main.jpg",
            "images": [
                {
                    "asset": "jeegee-pl-3-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Jeegee PL-3",
                },
            ],
        },
        {
            "slug": "jeegee-pl-4",
            "brand_slug": "jeegee",
            "name": "Jeegee PL-4",
            "description": "Četvororazni plug sa hidrauličnim podešavanjem dubine.",
            "key_features": [
                "Robusna konstrukcija",
                "Jednostavno održavanje",
                "Prilagodljivo traktorima",
            ],
            "horse_power": None,
            "year": None,
            "price_eur": None,
            "subcategory_slug": "plugovi",
            "main_image_asset": "jeegee-pl-4-main.jpg",
            "images": [
                {
                    "asset": "jeegee-pl-4-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Jeegee PL-4",
                },
            ],
        },
        {
            "slug": "jeegee-pl-5",
            "brand_slug": "jeegee",
            "name": "Jeegee PL-5",
            "description": "Petorazni plug za teže tipove zemljišta.",
            "key_features": [
                "Robusna konstrukcija",
                "Jednostavno održavanje",
                "Prilagodljivo traktorima",
            ],
            "horse_power": None,
            "year": None,
            "price_eur": None,
            "subcategory_slug": "plugovi",
            "main_image_asset": "jeegee-pl-5-main.jpg",
            "images": [
                {
                    "asset": "jeegee-pl-5-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Jeegee PL-5",
                },
            ],
        },
        {
            "slug": "jeegee-pl-6",
            "brand_slug": "jeegee",
            "name": "Jeegee PL-6",
            "description": "Šestorazni plug za velike ratarske površine.",
            "key_features": [
                "Robusna konstrukcija",
                "Jednostavno održavanje",
                "Prilagodljivo traktorima",
            ],
            "horse_power": None,
            "year": None,
            "price_eur": None,
            "subcategory_slug": "plugovi",
            "main_image_asset": "jeegee-pl-6-main.jpg",
            "images": [
                {
                    "asset": "jeegee-pl-6-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Jeegee PL-6",
                },
            ],
        },
        {
            "slug": "jeegee-sj-12",
            "brand_slug": "jeegee",
            "name": "Jeegee SJ-12",
            "description": "Sejalica sa 12 redova i preciznim doziranjem semena.",
            "key_features": [
                "Robusna konstrukcija",
                "Jednostavno održavanje",
                "Prilagodljivo traktorima",
            ],
            "horse_power": None,
            "year": None,
            "price_eur": None,
            "subcategory_slug": "sejalice",
            "main_image_asset": "jeegee-sj-12-main.jpg",
            "images": [
                {
                    "asset": "jeegee-sj-12-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Jeegee SJ-12",
                },
            ],
        },
        {
            "slug": "jeegee-sj-16",
            "brand_slug": "jeegee",
            "name": "Jeegee SJ-16",
            "description": "Pneumatska sejalica sa 16 redova za veće parcele.",
            "key_features": [
                "Robusna konstrukcija",
                "Jednostavno održavanje",
                "Prilagodljivo traktorima",
            ],
            "horse_power": None,
            "year": None,
            "price_eur": None,
            "subcategory_slug": "sejalice",
            "main_image_asset": "jeegee-sj-16-main.jpg",
            "images": [
                {
                    "asset": "jeegee-sj-16-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Jeegee SJ-16",
                },
            ],
        },
        {
            "slug": "jeegee-sj-4-prec",
            "brand_slug": "jeegee",
            "name": "Jeegee SJ-4-Prec",
            "description": "Precizna sejalica za kukuruz i suncokret, 4 reda.",
            "key_features": [
                "Robusna konstrukcija",
                "Jednostavno održavanje",
                "Prilagodljivo traktorima",
            ],
            "horse_power": None,
            "year": None,
            "price_eur": None,
            "subcategory_slug": "sejalice",
            "main_image_asset": "jeegee-sj-4-prec-main.jpg",
            "images": [
                {
                    "asset": "jeegee-sj-4-prec-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Jeegee SJ-4-Prec",
                },
            ],
        },
        {
            "slug": "jeegee-sj-6-prec",
            "brand_slug": "jeegee",
            "name": "Jeegee SJ-6-Prec",
            "description": "Precizna sejalica za kukuruz i suncokret, 6 redova.",
            "key_features": [
                "Robusna konstrukcija",
                "Jednostavno održavanje",
                "Prilagodljivo traktorima",
            ],
            "horse_power": None,
            "year": None,
            "price_eur": None,
            "subcategory_slug": "sejalice",
            "main_image_asset": "jeegee-sj-6-prec-main.jpg",
            "images": [
                {
                    "asset": "jeegee-sj-6-prec-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Jeegee SJ-6-Prec",
                },
            ],
        },
        {
            "slug": "jeegee-sj-8",
            "brand_slug": "jeegee",
            "name": "Jeegee SJ-8",
            "description": "Mehanička sejalica sa 8 redova za žitarice.",
            "key_features": [
                "Robusna konstrukcija",
                "Jednostavno održavanje",
                "Prilagodljivo traktorima",
            ],
            "horse_power": None,
            "year": None,
            "price_eur": None,
            "subcategory_slug": "sejalice",
            "main_image_asset": "jeegee-sj-8-main.jpg",
            "images": [
                {
                    "asset": "jeegee-sj-8-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Jeegee SJ-8",
                },
            ],
        },
        {
            "slug": "jeegee-tnj-12",
            "brand_slug": "jeegee",
            "name": "Jeegee TNJ-12",
            "description": "Kompaktna tanjirača za manje traktore.",
            "key_features": [
                "Robusna konstrukcija",
                "Jednostavno održavanje",
                "Prilagodljivo traktorima",
            ],
            "horse_power": None,
            "year": None,
            "price_eur": None,
            "subcategory_slug": "tanjirace",
            "main_image_asset": "jeegee-tnj-12-main.jpg",
            "images": [
                {
                    "asset": "jeegee-tnj-12-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Jeegee TNJ-12",
                },
            ],
        },
        {
            "slug": "jeegee-tnj-16",
            "brand_slug": "jeegee",
            "name": "Jeegee TNJ-16",
            "description": "Tanjirača sa 16 tanjira za plitku obradu zemljišta.",
            "key_features": [
                "Robusna konstrukcija",
                "Jednostavno održavanje",
                "Prilagodljivo traktorima",
            ],
            "horse_power": None,
            "year": None,
            "price_eur": None,
            "subcategory_slug": "tanjirace",
            "main_image_asset": "jeegee-tnj-16-main.jpg",
            "images": [
                {
                    "asset": "jeegee-tnj-16-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Jeegee TNJ-16",
                },
            ],
        },
        {
            "slug": "jeegee-tnj-20",
            "brand_slug": "jeegee",
            "name": "Jeegee TNJ-20",
            "description": "Tanjirača sa 20 tanjira, pojačan ram.",
            "key_features": [
                "Robusna konstrukcija",
                "Jednostavno održavanje",
                "Prilagodljivo traktorima",
            ],
            "horse_power": None,
            "year": None,
            "price_eur": None,
            "subcategory_slug": "tanjirace",
            "main_image_asset": "jeegee-tnj-20-main.jpg",
            "images": [
                {
                    "asset": "jeegee-tnj-20-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Jeegee TNJ-20",
                },
            ],
        },
        {
            "slug": "jeegee-tnj-24",
            "brand_slug": "jeegee",
            "name": "Jeegee TNJ-24",
            "description": "Tanjirača sa 24 tanjira za brzu pripremu setvene površine.",
            "key_features": [
                "Robusna konstrukcija",
                "Jednostavno održavanje",
                "Prilagodljivo traktorima",
            ],
            "horse_power": None,
            "year": None,
            "price_eur": None,
            "subcategory_slug": "tanjirace",
            "main_image_asset": "jeegee-tnj-24-main.jpg",
            "images": [
                {
                    "asset": "jeegee-tnj-24-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Jeegee TNJ-24",
                },
            ],
        },
        {
            "slug": "jeegee-tnj-28",
            "brand_slug": "jeegee",
            "name": "Jeegee TNJ-28",
            "description": "Tanjirača velike radne širine za veće posede.",
            "key_features": [
                "Robusna konstrukcija",
                "Jednostavno održavanje",
                "Prilagodljivo traktorima",
            ],
            "horse_power": None,
            "year": None,
            "price_eur": None,
            "subcategory_slug": "tanjirace",
            "main_image_asset": "jeegee-tnj-28-main.jpg",
            "images": [
                {
                    "asset": "jeegee-tnj-28-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Jeegee TNJ-28",
                },
            ],
        },
        {
            "slug": "saillong-sl1004",
            "brand_slug": "saillong",
            "name": "Saillong SL1004",
            "description": "Najsnažniji model u SL seriji za velika gazdinstva.",
            "key_features": [
                "Klimatizovana kabina",
                "Hidraulična dizalica",
                "Robusna konstrukcija",
            ],
            "horse_power": 100,
            "year": 2025,
            "price_eur": Decimal("35400.00"),
            "subcategory_slug": "traktori",
            "series_slug": "standardna-serija",
            "main_image_asset": "saillong-sl1004-main.jpg",
            "images": [
                {
                    "asset": "saillong-sl1004-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Saillong SL1004",
                },
            ],
        },
        {
            "slug": "saillong-sl454",
            "brand_slug": "saillong",
            "name": "Saillong SL454",
            "description": "Kompaktan traktor za manje posede i voćnjake.",
            "key_features": [
                "Klimatizovana kabina",
                "Hidraulična dizalica",
                "Robusna konstrukcija",
            ],
            "horse_power": 45,
            "year": 2022,
            "price_eur": Decimal("16900.00"),
            "subcategory_slug": "traktori",
            "series_slug": "standardna-serija",
            "main_image_asset": "saillong-sl454-main.jpg",
            "images": [
                {
                    "asset": "saillong-sl454-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Saillong SL454",
                },
            ],
        },
        {
            "slug": "saillong-sl604",
            "brand_slug": "saillong",
            "name": "Saillong SL604",
            "description": "Traktor srednje snage za ratarske i transportne radove.",
            "key_features": [
                "Klimatizovana kabina",
                "Hidraulična dizalica",
                "Robusna konstrukcija",
            ],
            "horse_power": 60,
            "year": 2023,
            "price_eur": Decimal("21800.00"),
            "subcategory_slug": "traktori",
            "series_slug": "standardna-serija",
            "main_image_asset": "saillong-sl604-main.jpg",
            "images": [
                {
                    "asset": "saillong-sl604-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Saillong SL604",
                },
            ],
        },
        {
            "slug": "saillong-sl704",
            "brand_slug": "saillong",
            "name": "Saillong SL704",
            "description": "Robustan traktor sa ojačanom transmisijom.",
            "key_features": [
                "Klimatizovana kabina",
                "Hidraulična dizalica",
                "Robusna konstrukcija",
            ],
            "horse_power": 70,
            "year": 2024,
            "price_eur": Decimal("24600.00"),
            "subcategory_slug": "traktori",
            "series_slug": "standardna-serija",
            "main_image_asset": "saillong-sl704-main.jpg",
            "images": [
                {
                    "asset": "saillong-sl704-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Saillong SL704",
                },
            ],
        },
        {
            "slug": "saillong-sl904",
            "brand_slug": "saillong",
            "name": "Saillong SL904",
            "description": "Snažan traktor od 90 KS za najzahtevnije ratarske i transportne radove.",
            "key_features": [
                "Velika vučna snaga",
                "Ojačana transmisija",
                "Komforna kabina",
            ],
            "horse_power": 90,
            "year": 2025,
            "price_eur": Decimal("32400.00"),
            "subcategory_slug": "traktori",
            "series_slug": "standardna-serija",
            "main_image_asset": "saillong-sl904-main.jpg",
            "images": [
                {
                    "asset": "saillong-sl904-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Saillong SL904",
                },
            ],
        },
        {
            "slug": "wuzheng-wz354",
            "brand_slug": "wuzheng",
            "name": "Wuzheng WZ354",
            "description": "Mini traktor pogodan za voćnjake i vinograde.",
            "key_features": [
                "Klimatizovana kabina",
                "Hidraulična dizalica",
                "Robusna konstrukcija",
            ],
            "horse_power": 35,
            "year": 2023,
            "price_eur": Decimal("12900.00"),
            "subcategory_slug": "traktori",
            "series_slug": "standardna-serija",
            "main_image_asset": "wuzheng-wz354-main.jpg",
            "images": [
                {
                    "asset": "wuzheng-wz354-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Wuzheng WZ354",
                },
            ],
        },
        {
            "slug": "wuzheng-wz504",
            "brand_slug": "wuzheng",
            "name": "Wuzheng WZ504",
            "description": "Kompaktan traktor od 50 KS, idealan za voćnjake i manja gazdinstva.",
            "key_features": [
                "Štedljiv motor",
                "Laka upravljivost",
                "Pristupačna cena",
            ],
            "horse_power": 50,
            "year": 2023,
            "price_eur": Decimal("19900.00"),
            "subcategory_slug": "traktori",
            "series_slug": "standardna-serija",
            "main_image_asset": "wuzheng-wz504-main.jpg",
            "images": [
                {
                    "asset": "wuzheng-wz504-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Wuzheng WZ504",
                },
            ],
        },
        {
            "slug": "wuzheng-wz604",
            "brand_slug": "wuzheng",
            "name": "Wuzheng WZ604",
            "description": "Univerzalni traktor srednje snage za mešovita gazdinstva.",
            "key_features": [
                "Klimatizovana kabina",
                "Hidraulična dizalica",
                "Robusna konstrukcija",
            ],
            "horse_power": 60,
            "year": 2024,
            "price_eur": Decimal("22400.00"),
            "subcategory_slug": "traktori",
            "series_slug": "standardna-serija",
            "main_image_asset": "wuzheng-wz604-main.jpg",
            "images": [
                {
                    "asset": "wuzheng-wz604-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Wuzheng WZ604",
                },
            ],
        },
        {
            "slug": "wuzheng-wz654",
            "brand_slug": "wuzheng",
            "name": "Wuzheng WZ654",
            "description": "Traktor sa pojačanom hidraulikom i udobnom kabinom.",
            "key_features": [
                "Klimatizovana kabina",
                "Hidraulična dizalica",
                "Robusna konstrukcija",
            ],
            "horse_power": 65,
            "year": 2024,
            "price_eur": Decimal("23900.00"),
            "subcategory_slug": "traktori",
            "series_slug": "standardna-serija",
            "main_image_asset": "wuzheng-wz654-main.jpg",
            "images": [
                {
                    "asset": "wuzheng-wz654-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Wuzheng WZ654",
                },
            ],
        },
        {
            "slug": "wuzheng-wz704",
            "brand_slug": "wuzheng",
            "name": "Wuzheng WZ704",
            "description": "Najnoviji model u WZ liniji, ekonomičan i pouzdan.",
            "key_features": [
                "Klimatizovana kabina",
                "Hidraulična dizalica",
                "Robusna konstrukcija",
            ],
            "horse_power": 70,
            "year": 2025,
            "price_eur": Decimal("25800.00"),
            "subcategory_slug": "traktori",
            "series_slug": "standardna-serija",
            "main_image_asset": "wuzheng-wz704-main.jpg",
            "images": [
                {
                    "asset": "wuzheng-wz704-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Wuzheng WZ704",
                },
            ],
        },
    ],
    "used_machines": [
        {
            "slug": "hzm-ml-35",
            "brand_slug": "hzm",
            "name": "HZM ML-35",
            "description": "Polovni mini utovarivač, redovno održavan, spreman za rad.",
            "key_features": [
                "Pouzdana hidraulika",
                "Robusna konstrukcija",
                "Servisna podrška",
            ],
            "horse_power": 35,
            "year": 2021,
            "price_eur": Decimal("9800.00"),
            "subcategory_slug": "mini-utovarivaci",
            "main_image_asset": "hzm-ml-35-main.jpg",
            "images": [
                {
                    "asset": "hzm-ml-35-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "HZM ML-35",
                },
            ],
        },
        {
            "slug": "hzm-th-40",
            "brand_slug": "hzm",
            "name": "HZM TH-40",
            "description": "Polovni telehendler, servisna knjiga uredna, spreman za rad.",
            "key_features": [
                "Pouzdana hidraulika",
                "Robusna konstrukcija",
                "Servisna podrška",
            ],
            "horse_power": 40,
            "year": 2021,
            "price_eur": Decimal("19300.00"),
            "subcategory_slug": "telehendleri",
            "main_image_asset": "hzm-th-40-main.jpg",
            "images": [
                {
                    "asset": "hzm-th-40-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "HZM TH-40",
                },
            ],
        },
        {
            "slug": "hzm-tl-90",
            "brand_slug": "hzm",
            "name": "HZM TL-90",
            "description": "Polovni teleskopski utovarivač, ispravna hidraulika i teleskop.",
            "key_features": [
                "Pouzdana hidraulika",
                "Robusna konstrukcija",
                "Servisna podrška",
            ],
            "horse_power": 90,
            "year": 2020,
            "price_eur": Decimal("18700.00"),
            "subcategory_slug": "teleskopski-utovarivaci",
            "main_image_asset": "hzm-tl-90-main.jpg",
            "images": [
                {
                    "asset": "hzm-tl-90-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "HZM TL-90",
                },
            ],
        },
        {
            "slug": "hzm-ub-55",
            "brand_slug": "hzm",
            "name": "HZM UB-55",
            "description": "Polovni utovarivač, očuvana hidraulika, niski sati rada.",
            "key_features": [
                "Pouzdana hidraulika",
                "Robusna konstrukcija",
                "Servisna podrška",
            ],
            "horse_power": 55,
            "year": 2022,
            "price_eur": Decimal("14600.00"),
            "subcategory_slug": "utovarivaci-bez-teleskopa",
            "main_image_asset": "hzm-ub-55-main.jpg",
            "images": [
                {
                    "asset": "hzm-ub-55-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "HZM UB-55",
                },
            ],
        },
        {
            "slug": "polovni-hzm-utovarivac",
            "brand_slug": "hzm",
            "name": "Polovni HZM utovarivač",
            "description": "Polovni čeoni utovarivač od 65 KS sa očuvanom hidraulikom.",
            "key_features": [
                "Očuvana hidraulika",
                "Snažan motor",
                "Pouzdan rad",
            ],
            "horse_power": 65,
            "year": 2020,
            "price_eur": Decimal("15900.00"),
            "main_image_asset": "polovni-hzm-utovarivac-main.jpg",
            "images": [
                {
                    "asset": "polovni-hzm-utovarivac-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Polovni HZM utovarivač",
                },
            ],
        },
        {
            "slug": "polovni-saillong-sl904",
            "brand_slug": "saillong",
            "name": "Polovni Saillong SL904",
            "description": "Polovni traktor od 55 KS, dobro održavan i spreman za sezonu.",
            "key_features": [
                "Dobro održavan",
                "Ojačana šasija",
                "Komforna kabina",
            ],
            "horse_power": 55,
            "year": 2021,
            "price_eur": Decimal("13400.00"),
            "main_image_asset": "polovni-saillong-sl904-main.jpg",
            "images": [
                {
                    "asset": "polovni-saillong-sl904-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Polovni Saillong SL904",
                },
            ],
        },
        {
            "slug": "polovni-traktor-agri-tracking-tb804",
            "brand_slug": "agri-tracking",
            "name": "Polovni traktor Agri Tracking TB804",
            "description": "Očuvan polovni traktor od 75 KS sa redovno servisiranim motorom.",
            "key_features": [
                "Redovno servisiran",
                "Očuvana kabina",
                "Spreman za rad",
            ],
            "horse_power": 75,
            "year": 2022,
            "price_eur": Decimal("18500.00"),
            "main_image_asset": "polovni-traktor-agri-tracking-tb804-main.jpg",
            "images": [
                {
                    "asset": "polovni-traktor-agri-tracking-tb804-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Polovni traktor Agri Tracking TB804",
                },
                {
                    "asset": "agri-tracking-real-03.jpg",
                    "order": 1,
                    "alt_text": "Polovni traktor Agri Tracking TB804 — galerija 1",
                },
                {
                    "asset": "agri-tracking-real-04.jpg",
                    "order": 2,
                    "alt_text": "Polovni traktor Agri Tracking TB804 — galerija 2",
                },
                {
                    "asset": "agri-tracking-real-17.jpg",
                    "order": 3,
                    "alt_text": "Polovni traktor Agri Tracking TB804 — galerija 3",
                },
                {
                    "asset": "agri-tracking-real-14.jpg",
                    "order": 4,
                    "alt_text": "Polovni traktor Agri Tracking TB804 — galerija 4",
                },
                {
                    "asset": "agri-tracking-real-06.jpg",
                    "order": 5,
                    "alt_text": "Polovni traktor Agri Tracking TB804 — galerija 5",
                },
                {
                    "asset": "agri-tracking-real-11.jpg",
                    "order": 6,
                    "alt_text": "Polovni traktor Agri Tracking TB804 — galerija 6",
                },
                {
                    "asset": "agri-tracking-real-05.jpg",
                    "order": 7,
                    "alt_text": "Polovni traktor Agri Tracking TB804 — galerija 7",
                },
                {
                    "asset": "agri-tracking-real-16.jpg",
                    "order": 8,
                    "alt_text": "Polovni traktor Agri Tracking TB804 — galerija 8",
                },
                {
                    "asset": "agri-tracking-real-27.jpg",
                    "order": 9,
                    "alt_text": "Polovni traktor Agri Tracking TB804 — galerija 9",
                },
                {
                    "asset": "agri-tracking-real-02.jpg",
                    "order": 10,
                    "alt_text": "Polovni traktor Agri Tracking TB804 — galerija 10",
                },
                {
                    "asset": "agri-tracking-real-30.jpg",
                    "order": 11,
                    "alt_text": "Polovni traktor Agri Tracking TB804 — galerija 11",
                },
                {
                    "asset": "agri-tracking-real-18.jpg",
                    "order": 12,
                    "alt_text": "Polovni traktor Agri Tracking TB804 — galerija 12",
                },
                {
                    "asset": "agri-tracking-real-24.jpg",
                    "order": 13,
                    "alt_text": "Polovni traktor Agri Tracking TB804 — galerija 13",
                },
                {
                    "asset": "agri-tracking-real-28.jpg",
                    "order": 14,
                    "alt_text": "Polovni traktor Agri Tracking TB804 — galerija 14",
                },
                {
                    "asset": "agri-tracking-real-12.jpg",
                    "order": 15,
                    "alt_text": "Polovni traktor Agri Tracking TB804 — galerija 15",
                },
            ],
        },
        {
            "slug": "polovni-tulip-mix-6m3",
            "brand_slug": "tulip",
            "name": "Polovni Tulip MIX 6 m³",
            "description": "Polovni rasipač stajnjaka zapremine 6 m³ u dobrom stanju.",
            "key_features": [
                "Zapremina 6 m³",
                "Pocinkovano kućište",
                "Robusna konstrukcija",
            ],
            "horse_power": 35,
            "year": 2018,
            "price_eur": Decimal("4200.00"),
            "main_image_asset": "polovni-tulip-mix-6m3-main.jpg",
            "images": [
                {
                    "asset": "polovni-tulip-mix-6m3-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Polovni Tulip MIX 6 m³",
                },
            ],
        },
        {
            "slug": "polovni-wuzheng-wz504",
            "brand_slug": "wuzheng",
            "name": "Polovni Wuzheng WZ504",
            "description": "Kompaktan polovni traktor od 45 KS, štedljiv i jednostavan za održavanje.",
            "key_features": [
                "Štedljiv motor",
                "Niski sati rada",
                "Jeftino održavanje",
            ],
            "horse_power": 45,
            "year": 2019,
            "price_eur": Decimal("9800.00"),
            "main_image_asset": "polovni-wuzheng-wz504-main.jpg",
            "images": [
                {
                    "asset": "polovni-wuzheng-wz504-gallery-1.jpg",
                    "order": 0,
                    "alt_text": "Polovni Wuzheng WZ504",
                },
            ],
        },
    ],
    "headline_specs": None,
    "brochures": [
        {
            "product_slug": "agri-tracking-tb704",
            "title": "Agri Tracking TB704",
            "pdf_asset": "agri-tracking-tb704-agri-tracking-tb704-brosura.pdf",
            "cover_thumbnail_asset": "agri-tracking-tb704-cover.jpg",
        },
    ],
    "testimonials": [
        {
            "product_slug": "agri-tracking-tb1004",
            "author_name": "Zoran Ilić",
            "location": "poljoprivrednik iz Vrbasa",
            "quote": "TB1004 nam je promenio radni dan — GPS priprema i klimatizovana kabina znače da ekipa radi duže i preciznije, čak i kad je napolju vrelo. Najbolja investicija u poslednje tri godine.",
            "order": 1,
            "photo_asset": "jovan-jovanovic-test.jpg",
        },
        {
            "product_slug": "agri-tracking-tb1004",
            "author_name": "Aleksandar Perić",
            "location": "poljoprivrednik iz Sombora",
            "quote": "Na velikom posedu je TB1004 pravi izbor — GPS vođenje štedi i gorivo i vreme, a snaga je dovoljna za teže priključke bez gubljenja obrtaja.",
            "order": 1,
            "photo_asset": "petar-petrovic-test.jpg",
        },
        {
            "product_slug": "agri-tracking-tb1004",
            "author_name": "Miroslav Kovačević",
            "location": "poljoprivrednik iz Subotice",
            "quote": "Radimo na 200+ hektara i TB1004 izdrži ceo dan bez zastoja. Klimatizovana kabina je posebno bitna leti — ekipa radi duže i sa manje umora.",
            "order": 2,
            "photo_asset": "ivan-ivanovic-test.jpg",
        },
        {
            "product_slug": "agri-tracking-tb604",
            "author_name": "Ivan Stanković",
            "location": "poljoprivrednik iz Rume",
            "quote": "TB604 koristim za voćnjak i manje parcele — lagan je za manevrisanje, a snage ima dovoljno i za priključnu kosačicu.",
            "order": 1,
            "photo_asset": "ivan-ivanovic-test.jpg",
        },
        {
            "product_slug": "agri-tracking-tb604",
            "author_name": "Milica Radovanović",
            "location": "poljoprivrednica iz Bačke Palanke",
            "quote": "Imam manje imanje i baš mi je trebao kompaktan traktor koji lako manevriše između redova. TB604 je upravo to — okretan, štedljiv i dovoljno snažan za sve što mi treba.",
            "order": 2,
        },
        {
            "product_slug": "agri-tracking-tb604",
            "author_name": "Jovan Nikolić",
            "location": "poljoprivrednik iz Inđije",
            "quote": "Odličan traktor za manje gazdinstvo — ekonomičan, pouzdan i lak za održavanje. Preporučujem svima koji traže kompaktnu mašinu.",
            "order": 2,
            "photo_asset": "jovan-jovanovic-test.jpg",
        },
        {
            "product_slug": "agri-tracking-tb704",
            "author_name": "Nikola Savic",
            "location": "poljoprivrednik iz Zrenjanina",
            "quote": "TB704 koristim svaki dan za redovne radove oko imanja. Lak je za upravljanje, ne trosi mnogo goriva i do sada nije imao nijedan kvar.",
            "order": 0,
            "photo_asset": "ivan-ivanovic-test.jpg",
        },
        {
            "product_slug": "agri-tracking-tb704",
            "author_name": "Vladimir Tomić",
            "location": "poljoprivrednik iz Pančeva",
            "quote": "TB704 mi je idealan za srednje parcele — dovoljno snage za plug i frezu, a opet lako uđe i u uže prilaze. Potrošnja goriva me je prijatno iznenadila.",
            "order": 1,
            "photo_asset": "petar-petrovic-test.jpg",
        },
        {
            "product_slug": "agri-tracking-tb704",
            "author_name": "Goran Đurić",
            "location": "poljoprivrednik iz Kovina",
            "quote": "Uzeo sam TB704 pre godinu dana i do sada nijednog problema. Servis je brz kad zatreba, a rezervni delovi uvek na stanju.",
            "order": 2,
            "photo_asset": "jovan-jovanovic-test.jpg",
        },
        {
            "product_slug": "agri-tracking-tb804",
            "author_name": "Petar Petrović",
            "location": "poljoprivrednik iz Kikinde",
            "quote": "Agri Tracking TB804 vozim već drugu sezonu — hidraulika je snažna, kabina tiha, a servis je uvek dostupan kad zatreba. Traktor koji izdrži pun radni dan bez iznenađenja.",
            "order": 0,
            "photo_asset": "petar-petrovic-test.jpg",
        },
        {
            "product_slug": "agri-tracking-tb804",
            "author_name": "Dragan Mitrović",
            "location": "poljoprivrednik iz Vršca",
            "quote": "Pre TB804 menjao sam traktore na svakih par godina. Ovaj je prvi koji zaista prati tempo krupnog poseda — snaga na priključku je odlična, a potrošnja iznenađujuće niska.",
            "order": 1,
            "photo_asset": "ivan-ivanovic-test.jpg",
        },
        {
            "product_slug": "agri-tracking-tb804",
            "author_name": "Slobodan Jovanović",
            "location": "poljoprivrednik iz Šapca",
            "quote": "Radim sa TB804 na oranicama i pri transportu bala — kabina je udobna i posle deset sati u sedištu, a hidraulika odgovara i na najzahtevnije priključke.",
            "order": 2,
            "photo_asset": "jovan-jovanovic-test.jpg",
        },
    ],
    "similar": [
        {
            "product_slug": "agri-tracking-tb704",
            "related_product_slug": "jeegee-sj-8",
            "order": 0,
        },
        {
            "product_slug": "agri-tracking-tb704",
            "related_product_slug": "jeegee-tnj-16",
            "order": 1,
        },
        {
            "product_slug": "agri-tracking-tb704",
            "related_product_slug": "jeegee-sj-12",
            "order": 2,
        },
    ],
    "blog": {
        "category": {
            "slug": "ratarstvo",
            "name": "Ratarstvo",
            "description": "Saveti i novosti iz oblasti ratarske proizvodnje i obrade zemljišta.",
        },
        "tag": {
            "slug": "zetva",
            "name": "Žetva",
        },
        "posts": [
            {
                "slug": "kako-odabrati-traktor",
                "title": "Kako odabrati traktor za vaše gazdinstvo",
                "perex": "Snaga, transmisija i hidraulika — na šta obratiti pažnju pri kupovini.",
                "body": "Odabir pravog traktora zavisi od veličine poseda i vrste radova. Objašnjavamo razliku u konjskim snagama i zašto je kvalitetna hidraulika ključna.",
            },
            {
                "slug": "odrzavanje-mehanizacije-pred-zetvu",
                "title": "Održavanje mehanizacije pred žetvu",
                "perex": "Redovan servis pred sezonu štedi vreme i sprečava skupe kvarove.",
                "body": "Pred žetvu je neophodno proveriti remenje, ležajeve i hidraulične vodove. Donosimo kratku čeklistu održavanja koja produžava vek vaše mehanizacije.",
            },
            {
                "slug": "pet-saveta-za-prolecnu-setvu",
                "title": "Pet saveta za prolećnu setvu",
                "perex": "Kako da pripremite njivu i mašine za uspešnu prolećnu setvu.",
                "body": "Prolećna setva zahteva pažljivu pripremu zemljišta i ispravno podešene mašine. U ovom tekstu donosimo pet praktičnih saveta koji će vam pomoći da povećate prinos.",
            },
        ],
    },
}
